const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const ObjectId = Schema.ObjectId;
var dayjs = require('dayjs');
const roles = require('../utils/roles');
var now = dayjs()

const UserAccount = new Schema({
  userid: Number,
  email: String,
  api_token: String,
  roles: [Number],
  data: [{name: String, value: String, size: String, type: String, created_at: Date}],
  account_type: String,
  date: Date
});

UserAccount.statics.findByEmailOrId = function findByEmailOrId(data, cb){
  if (!data) return cb(new Error('No data provided'));
  if (data.email) {
    this.findOne({email: data.email}, function(err, result){
      if (err) return cb(err);
      if (!result) return cb(null, false);
      return cb(null, result);
    });
  } else if (data.userid) {
    this.findOne({userid: data.userid}, function(err, result){  
      if (err) return cb(err);
      if (!result) return cb(null, false);
      return cb(null, result);
    });
  }
};


UserAccount.statics.appendRole = function appendRole(user, role, cb){
  if (!user) return cb(new Error('No user provided'));
  if (!role) return cb(new Error('No role provided'));
  //if (roles.USER || roles.PREMIUM || roles.MOD || roles.ADMIN || roles.OWNER !== role) return cb(new Error('Invalid role'));
  this.findOne({userid: user.userid}, function(err, result){  
    if (err) return cb(err);
    if (user.roles.includes(role)) return cb(new Error('User already has that role'));
    user.roles.push(role);
    user.save(function(err, result){
      if (err) return cb(err);
      return cb(null, result);
    });
  });
};

// Auto generated by CoPilot and modified by Phil K for use in the project
UserAccount.statics.addImageOrFile = function addImageOrFile(user, data, cb){
  if (!user) return cb(new Error('No user provided'));
  if (!data) return cb(new Error('No data provided'));
  if (!data.userid) return cb(new Error('No userid provided'));
  if (!data.name) return cb(new Error('No name provided'));
  if (!data.value) return cb(new Error('No value provided'));
  if (!data.size) return cb(new Error('No size provided'));
  if (!data.type) return cb(new Error('No type provided'));
  this.findOne({userid: user.userid}, function(err, result){
    if (err) return cb(err);
    if (!result) return cb(null, false);
    result.data.push({name: data.name, value: data.value, size: data.size, type: data.type, created_at: now});
    result.save(function(err, result){
      if (err) return cb(err);
      return cb(null, result);
    });
  });
};

UserAccount.statics.findOrCreate = function findOrCreate(profile, cb){
  this.findOne({userid : profile.id},function(err,result){ 
      if(!result){
        var userObj = new UserAccount({
          userid: profile.id,
          email: profile.email,
          api_token: '',
          roles: [0],
          data: [],
          account_type: '',
          date: now
        })
        userObj.save(function(err, result){
          if (err) return cb(err);
          return cb(null, result);
        });
          // userObj.email = profile.email;
          // userObj.account_type = profile.premium_type;
          // userObj.userid = profile.id;
          // userObj.api_token = null;
          // userObj.roles = [];
          // userObj.data = [];
          // userObj.date = now;
          // userObj.save(cb);
      }else{
          cb(err,result);
      }
  });
};

var exportUser = mongoose.model('UserAccount', UserAccount);

module.exports = exportUser;